# This file was generated by GoReleaser. DO NOT EDIT.
cask "crie" do
  name "crie"
  desc "Universal meta-linter using containerized execution "
  homepage "https://github.com/tyhal/crie"
  version "0.20.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "crie"
  bash_completion "res/completion/crie.bash"
  zsh_completion "res/completion/crie.zsh"
  fish_completion "res/completion/crie.fish"

  on_linux do
    on_intel do
      url "https://github.com/tyhal/crie/releases/download/v#{version}/crie_#{version}_linux_amd64.tar.gz"
      sha256 "a08e57af02ffa0def4cb346fb8ab8ad34cb49e35c994d0c7ed8d6378bc23da6c"
    end
  end

  # No zap stanza required
end
