# This file was generated by GoReleaser. DO NOT EDIT.
cask "crie" do
  name "crie"
  desc "Universal meta-linter using containerized execution "
  homepage "https://github.com/tyhal/crie"
  version "0.20.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "crie"
  bash_completion "res/completion/crie.bash"
  zsh_completion "res/completion/crie.zsh"
  fish_completion "res/completion/crie.fish"

  on_linux do
    on_intel do
      url "https://github.com/tyhal/crie/releases/download/v#{version}/crie_#{version}_linux_amd64.tar.gz"
      sha256 "8ee8436aabe6ca240eafc5c956c37f5d9c63de485a936f10fcb75e1c2852e4ea"
    end
  end

  # No zap stanza required
end
