# This file was generated by GoReleaser. DO NOT EDIT.
cask "crie" do
  name "crie"
  desc "Universal meta-linter using containerized execution "
  homepage "https://github.com/tyhal/crie"
  version "0.20.11"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "crie"
  bash_completion "res/completion/crie.bash"
  zsh_completion "res/completion/crie.zsh"
  fish_completion "res/completion/crie.fish"

  on_macos do
    on_arm do
      url "https://github.com/tyhal/crie/releases/download/v#{version}/crie_#{version}_darwin_arm64.tar.gz"
      sha256 "1ef57a4c1633dd607b9453700612918c27598bce45233f6491d11c114006d6c5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/tyhal/crie/releases/download/v#{version}/crie_#{version}_linux_amd64.tar.gz"
      sha256 "c375bf6b05d478f9806d088dabd25a8570c7b5c723fc0048e39768033bd00a06"
    end
  end

  # No zap stanza required
end
