name: crie
permissions:
  contents: read
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
jobs:
  crie-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Fetch base ref for PR
        if: github.event_name == 'pull_request'
        run: git fetch origin ${{ github.base_ref }}:refs/remotes/origin/${{ github.base_ref }}
      - name: Run crie all
        uses: tyhal/crie-action@dc2ddc3294821a43818a025525aebc08c8fc1179 # main
        with:
          command: lnt
          lint_continue: 'true'
          lint_passes: 'true'
          lint_git_diff: ${{ github.event_name == 'pull_request'  && 'true' || 'false' }}
          lint_git_target: ${{ github.event_name == 'pull_request' && format('origin/{0}', github.base_ref || github.ref_name) || '' }}
      - name: Ensure no diff
        run: git diff --exit-code
